server:
  port: 80
  database: /home/filebrowser/data/database.db
  cacheDir: /home/filebrowser/data/cache
  sources:
    - path: /files
      name: Files
      config:
        defaultEnabled: true

auth:
  adminUsername: admin
  methods:
    password:
      enabled: true
      minLength: 12

frontend:
  name: Arc Files
