FROM caddy:2.11.4-builder AS builder

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    xcaddy build \
      --with github.com/caddy-dns/porkbun@v0.3.1

FROM caddy:2.11.4

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
